title: MFT Secure Transport Hands-On Exercises
description: Self-paced hands-on labs to discover the MFT Secure Transport product
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
classes: wide

url: "https://axway-university-1.github.io"
baseurl: "/mft-exercises"

plugins:
  - jekyll-remote-theme